language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: QN53RaGbNiUM9XFop5G5qAJxwsp40XZJyXhGk8xO9zH3p2jTmiEXYV7gmf+8qwIP3oy/qe403wrXCx81e7DjknMdOF9vI0h/MCwddeYD2oluH2V3a3MeA0t3YRaxAp72We8SxQgDr5/uOEOdkfHfr2dwifGITrsqb/yj5QKrlbkoZT6P3OkkCndKRytEzHkUp+PNTwt9xYiO4cVFCvHPOH6/BTxEgxQUSAJ6IbrKXlk6wbZyROFc0m7H420VhwTcfNejYBwegYHKxc3w9rOZrngHvHmVkikjfjiDW7b2ClObYpjBfYaMQ7RinBguH98qao90JbHzyYdDWOdgpGepMhi8NA8m/g08eAmXW9sNiyYGGjtI4SHTtxh9YrxZLdqP3PjLS6ZsW0/R4qkS53FXhoRNY+ni51gFyPRlBn0+yQT2SKrTOUUhHQAP1KLhQX/dLvYUW64pc7e/lg0yEVdAZpcGzMrqLlh2STARlpxDFIDjNCAqpPF9EmqowBYchcAxtL94f1qEKgr0MCtuHEVij4nESMyq71LdWM6Po3x0v2Bgsa84IPR1K7qbApc12TC5tWI/yqSGF8T4axNZ4FWluySHbHJx/JRF4rYKCCwnQXKCxW6GNdh6OTswZQ9sXvp9CGFy6tAoX5p9jVPTcKGM3hTU73NHLxEtNcEcgYOzV1Y=
  strategy: git
  app: pomodorro
  on:
    repo: serwus79/pomodorro
