language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
deploy:
  provider: heroku
  api_key:
    secure: G96Yf7dwCwi6qbTdG/jGidZ0SsVWS3Ycs/Zaw0IMR9Hi9jiQEDmqnyDJJp9Nv7NTSxMdw8yXtSG6NsXAJeulH/InUKiUuj5CIt8miNHyaEJo99sgrB2ZLGX1rniUQl7kbXtK53ZLojoMYQ8E0On4aPImUR39pW18UHGQF1d7tquug/K/yi2nkQfrTQ3EK85xzTs924jXadif8WICRIYAMNfdlYe+iJQtVPiO8Hebo/7dHBymtnbHocDMjWDpRgJz2UeFvNdMe1nqTFvwB7gIBmHue2e5eTTdWsKhQu3AeRy/h5O6bCIt3iP9mGumSd5z+8voNhRxjvM6oi4Xloal3NP4VchUM3K2Qh94zAG8B38CZilid5cPyQ/6OzgDLp1e7AbDQ9SFaW+Y6+0Ep0Y5ypFFbOutyakMziQ/kEaISR5G4s9uZT/muNyteAiSYW59T0+fRt4h6fXn9zUeP2kmaZHYsd7KuSYSBcTtVnZEcuoDihO6FX2moV6A4hX8OcbykkgsiULSyyiqpC7H8m6cAsB2NG+ZqiUmT38L0RrI/WutmzKN2WNqkaOqZi+917AgeWNrbyZgbqOkcDlk49u7k6oZCmN+gZNGMu/FRulz/bxEyeU25dK1apJ84uJ2flj3m0bX6rOpFlffgJx3Br3ht0XWegniqtiRSNedJzTCNP8=
  app: pomodorro
  on:
    repo: serwus79/pomodorro
